<?php
namespace Admidio\Components\Entity;

use Admidio\Changelog\Entity\LogChanges;
use Admidio\Changelog\Service\ChangelogService;
use Admidio\Hooks\Hooks;
use Admidio\Documents\Entity\Folder;
use Admidio\Infrastructure\Exception;
use Admidio\Infrastructure\Database;
use Admidio\Infrastructure\Entity\Entity;
use Admidio\Infrastructure\Plugins\PluginRegistry;
use Admidio\Infrastructure\Plugins\PluginWidget;
use Admidio\UI\Presenter\InventoryPresenter;

/**
 * @brief Handle different components of Admidio (e.g. system, plugins or modules) and manage them in the database
 *
 * The class search in the database table **adm_components** for a specific component
 * and loads the data into this object. A component could be per default the **SYSTEM**
 * itself, a module or a plugin. There are methods to check the version of the system.
 *
 * **Code example**
 * ```
 * // check if database and filesystem have same version
 * try {
 *     $systemComponent = new Component($gDb);
 *     $systemComponent->readDataByColumns(array('com_type' => 'SYSTEM', 'com_name_intern' => 'CORE'));
 *     $systemComponent->checkDatabaseVersion(true, 'administrator@example.com');
 * } catch(Throwable $e) {
 *     $e->showHtml();
 * }
 * ```
 * @copyright The Admidio Team
 * @see https://www.admidio.org/
 * @license https://www.gnu.org/licenses/gpl-2.0.html GNU General Public License v2.0 only
 */
class Component extends Entity
{
    /**
     * Constructor that will create an object of a recordset of the table adm_component.
     * If the id is set than the specific component will be loaded.
     * @param Database $database Object of the class Database. This should be the default global object **$gDb**.
     * @param int $comId The recordset of the component with this id will be loaded.
     *                           If com_id isn't set than an empty object of the table is created.
     * @throws Exception
     */
    public function __construct(Database $database, int $comId = 0)
    {
        parent::__construct($database, TBL_COMPONENTS, 'com', $comId);
    }

    /**
     * Whether a change to this component belongs in the change history.
     *
     * The table holds two very different things. A plugin is added and removed by an administrator,
     * which is exactly the kind of decision an audit trail exists for. The rows of the core and of
     * its modules are written by the updater, and their versions change on every Admidio update -
     * logging those would bury the decisions somebody actually made under a list of version bumps.
     *
     * The distinction is in the data rather than in a flag, and it is made here rather than in
     * Entity: which rows of a table are worth logging is knowledge of that table.
     * @return bool
     * @throws Exception
     */
    private function isLoggedComponent(): bool
    {
        return (string)$this->getValue('com_type') === PluginRegistry::COMPONENT_TYPE;
    }

    /**
     * Log the creation of a plugin, which is what installing one is.
     * @return bool
     * @throws Exception
     */
    public function logCreation(): bool
    {
        return $this->isLoggedComponent() && parent::logCreation();
    }

    /**
     * Log the removal of a plugin.
     * @return bool
     * @throws Exception
     */
    public function logDeletion(): bool
    {
        return $this->isLoggedComponent() && parent::logDeletion();
    }

    /**
     * Log a change to a plugin, which is what updating one to a new version is.
     * @param array $logChanges Array of all changes, generated by the save method
     * @return bool
     * @throws Exception
     */
    public function logModifications(array $logChanges): bool
    {
        return $this->isLoggedComponent() && parent::logModifications($logChanges);
    }

    /**
     * Point the log entry of a plugin at the plugin itself.
     *
     * The settings of a plugin name its component record as their related object, so that the change
     * history of one plugin can be read on its own. Installing and removing it are changes to that
     * record, so they name it too - otherwise the two halves of a plugin's history could not be
     * asked for together.
     * @param LogChanges $logEntry
     * @return void
     * @throws Exception
     */
    protected function adjustLogEntry(LogChanges $logEntry): void
    {
        parent::adjustLogEntry($logEntry);

        $logEntry->setLogRelated((string)$this->getValue('com_uuid'), $this->readableName());
    }

    /**
     * @return string|null Returns the hook ID of this entity.
     * @see Entity::getHookId()
     */
    public function getHookId(): ?string
    {
        return 'component';
    }

    /**
     * Check version of component in database against the version of the file system.
     * There will be different messages shown if versions aren't equal. If database has minor
     * version than a link to update the database will be shown. If filesystem has minor version
     * than a link to download current version will be shown.
     * @throws Exception SYS_DATABASE_VERSION_INVALID
     *                      SYS_FILESYSTEM_VERSION_INVALID
     * @return void Nothing will be returned. If the versions aren't equal a message will be shown.
     */
    public function checkDatabaseVersion()
    {
        global $gLogger;

        $dbVersion = $this->getValue('com_version');
        if ($this->getValue('com_beta') > 0) {
            $dbVersion .= '-Beta.' . $this->getValue('com_beta');
        }

        $filesystemVersion = ADMIDIO_VERSION;
        if (ADMIDIO_VERSION_BETA > 0) {
            $filesystemVersion .= '-Beta.' . ADMIDIO_VERSION_BETA;
        }

        if ($this->getValue('com_update_completed') === '') {
            $errorMessage = 'The update to version ' . $filesystemVersion . ' must be done!<br />
                The last update step was step ' . $this->getValue('com_update_step') .
                ' of version ' . $dbVersion . '.';
            $gLogger->warning($errorMessage);

            throw new Exception($errorMessage);
        } elseif ($this->getValue('com_update_completed') !== true) {
            $errorMessage = 'The update to version ' . $filesystemVersion . ' was not successfully finished!<br />
                The last update step that was successfully performed was step ' . $this->getValue('com_update_step') .
                ' of version ' . $dbVersion . '.';
            $gLogger->warning($errorMessage);

            throw new Exception($errorMessage);
        }

        $returnCode = version_compare($dbVersion, $filesystemVersion);

        if ($returnCode === -1) { // database has minor version
            $gLogger->warning(
                'UPDATE: Database-Version is lower than the filesystem!',
                array('versionDB' => $dbVersion, 'versionFileSystem' => $filesystemVersion)
            );

            throw new Exception('SYS_DATABASE_VERSION_INVALID', array($dbVersion, ADMIDIO_VERSION_TEXT,
                                   '<a href="' . ADMIDIO_URL . FOLDER_INSTALLATION . '/update.php">', '</a>'));
        }
        if ($returnCode === 1) { // filesystem has minor version
            $gLogger->warning(
                'UPDATE: Filesystem-Version is lower than the database!',
                array('versionDB' => $dbVersion, 'versionFileSystem' => $filesystemVersion)
            );

            throw new Exception('SYS_FILESYSTEM_VERSION_INVALID', array($dbVersion, ADMIDIO_VERSION_TEXT,
                                   '<a href="' . ADMIDIO_HOMEPAGE . 'download.php">', '</a>'));
        }
    }

    /**
     * This method checks if the current user is allowed to edit and administrate the component. Therefore,
     * special checks for each component were done.
     *
     * The answer passes through the **component_administrable** filter, which receives the answer and
     * the name of the component. It is the one place that decides who may administrate a module, for
     * the menu, for the modules themselves and for the CLI, so a plugin that adds a right of its own
     * changes it here instead of in every module. It has to answer with a **bool**, which
     * Hooks::applyTypedFilters() enforces: a permission must not be decided by whatever happens to be
     * truthy. A filter can grant as well as revoke, so a callback that only wants to restrict has to
     * return the answer it was given unless it means to widen it.
     *
     * @param string $componentName The name of the component that is stored in the column com_name_intern e.g. GROUPS-ROLES
     * @return bool Return true if the current user is allowed to administrate the component
     * @throws \InvalidArgumentException
     * @throws \UnexpectedValueException|Exception
     */
    public static function isAdministrable(string $componentName): bool
    {
        return Hooks::applyTypedFilters('component_administrable', self::checkAdministrable($componentName), $componentName);
    }

    /**
     * The rights of Admidio itself, without the hook. isAdministrable() is the answer everybody uses.
     * @param string $componentName The name of the component.
     * @return bool Return true if the current user is allowed to administrate the component
     * @throws \InvalidArgumentException
     * @throws \UnexpectedValueException|Exception
     */
    private static function checkAdministrable(string $componentName): bool
    {
        global $gCurrentUser;

        if (self::isVisible($componentName)) {
            switch ($componentName) {
                case 'ANNOUNCEMENTS':
                    if ($gCurrentUser->isAdministratorAnnouncements()) {
                        return true;
                    }
                    break;

                case 'CATEGORY-REPORT':
                    if ($gCurrentUser->checkRolesRight('rol_all_lists_view')) {
                        return true;
                    }
                    break;

                case 'EVENTS':
                    if ($gCurrentUser->isAdministratorEvents()) {
                        return true;
                    }
                    break;

                case 'DOCUMENTS-FILES':
                    if ($gCurrentUser->isAdministratorDocumentsFiles()) {
                        return true;
                    }
                    break;

                case 'INVENTORY':
                    if ($gCurrentUser->isAdministratorInventory()) {
                        return true;
                    }
                    break;

                case 'FORUM':
                    if ($gCurrentUser->isAdministratorForum()) {
                        return true;
                    }
                    break;

                case 'LINKS':
                    if ($gCurrentUser->isAdministratorWeblinks()) {
                        return true;
                    }
                    break;

                case 'GROUPS-ROLES':
                    if ($gCurrentUser->isAdministratorRoles()) {
                        return true;
                    }
                    break;

                case 'CONTACTS':
                    if ($gCurrentUser->isAdministratorUsers()) {
                        return true;
                    }
                    break;

                case 'PHOTOS':
                    if ($gCurrentUser->isAdministratorPhotos()) {
                        return true;
                    }
                    break;

                case 'PROFILE':
                    if ($gCurrentUser->hasRightEditProfile($gCurrentUser)) {
                        return true;
                    }
                    break;

                case 'REGISTRATION':
                    if ($gCurrentUser->isAdministratorRegistration()) {
                        return true;
                    }
                    break;

                case 'CORE': // fallthrough
                case 'CATEGORIES': // fallthrough
                case 'MENU': // fallthrough
                case 'MESSAGES': // fallthrough
                case 'ORGANIZATIONS': // fallthrough
                case 'PREFERENCES': // fallthrough
                case 'PLUGINS': // fallthrough
                case 'ROOMS':
                    if ($gCurrentUser->isAdministrator()) {
                        return true;
                    }
                    break;

                default:
                    /*
                     * A plugin is administrated by an organization administrator, the same right
                     * that governs the plugin manager itself. A plugin that wants a right of its
                     * own does not add a case here; it answers the component_administrable filter.
                     */
                    if (PluginRegistry::get($componentName) !== null && $gCurrentUser->isAdministrator()) {
                        return true;
                    }
                    break;
            }
        }

        return false;
    }

    /**
     * This method checks if the current user is allowed to view the component. Therefore,
     * special checks for each component were done.
     *
     * The answer passes through the **component_visible** filter, which receives the answer and the
     * name of the component. It decides which entries the menu shows, which modules may be opened and
     * which commands the CLI offers, so it is a permission decision: the filter has to answer with a
     * **bool** and it can grant as well as revoke. See isAdministrable() for the rest of the contract.
     *
     * @param string $componentName The name of the component that is stored in the column com_name_intern e.g. GROUPS-ROLES
     * @return bool Return true if the current user is allowed to view the component
     * @throws \InvalidArgumentException
     * @throws \UnexpectedValueException|Exception
     */
    public static function isVisible(string $componentName): bool
    {
        return Hooks::applyTypedFilters('component_visible', self::checkVisible($componentName), $componentName);
    }

    /**
     * The rights of Admidio itself, without the hook. isVisible() is the answer everybody uses.
     * @param string $componentName The name of the component.
     * @return bool Return true if the current user is allowed to view the component
     * @throws \InvalidArgumentException
     * @throws \UnexpectedValueException|Exception
     */
    private static function checkVisible(string $componentName): bool
    {
        global $gValidLogin, $gCurrentUser, $gSettingsManager, $gDb;

        switch ($componentName) {
            case 'CORE': // fallthrough
            case 'CONTACTS':
                if ($gValidLogin) {
                    return true;
                }
                break;

            case 'ANNOUNCEMENTS':
                if ($gSettingsManager->getInt('announcements_module_enabled') === 1
                || ($gSettingsManager->getInt('announcements_module_enabled') === 2 && $gValidLogin)) {
                    return true;
                }
                break;

            case 'CATEGORY-REPORT':
                if ($gSettingsManager->getBool('category_report_module_enabled')
                && $gCurrentUser->checkRolesRight('rol_all_lists_view')) {
                    return true;
                }
                break;

            case 'CHANGELOG':
                // The change history is visible as soon as the user may read the log of at least
                // one database table, which is not restricted to administrators: the administrator
                // of a single module may read the log of that module, and every user may read the
                // history of his/her own profile. getReadableTables() is the same method the
                // module itself uses, and it also evaluates changelog_module_enabled, so the menu
                // entry disappears when the changelog is switched off or limited to administrators.
                if ($gValidLogin && count(ChangelogService::getReadableTables($gCurrentUser)) > 0) {
                    return true;
                }
                break;

            case 'EVENTS':
                if ($gSettingsManager->getInt('events_module_enabled') === 1
                || ($gSettingsManager->getInt('events_module_enabled') === 2 && $gValidLogin)) {
                    return true;
                }
                break;

            case 'DOCUMENTS-FILES':
                if ($gSettingsManager->getInt('documents_files_module_enabled') === 1
                || ($gSettingsManager->getInt('documents_files_module_enabled') === 2 && $gValidLogin)) {
                    try {
                        $documentsRootFolder = new Folder($gDb);
                        $documentsRootFolder->getFolderForDownload('');
                        return true;
                    } catch (Exception $e) {
                        return false;
                    }
                }
                break;

            case 'INVENTORY':
                if ($gSettingsManager->getInt('inventory_module_enabled') === 1
                || ($gSettingsManager->getInt('inventory_module_enabled') === 2 && $gValidLogin)
                || ($gSettingsManager->getInt('inventory_module_enabled') === 3 && $gCurrentUser->isAdministratorInventory())
                || ($gSettingsManager->getInt('inventory_module_enabled') === 4 && ($gCurrentUser->isAdministratorInventory() || InventoryPresenter::isCurrentUserKeeper()))
                || ($gSettingsManager->getInt('inventory_module_enabled') === 5 && $gCurrentUser->isAllowedToViewInventory())) {
                    return true;
                }
                break;

            case 'FORUM':
                if ($gSettingsManager->getInt('forum_module_enabled') === 1
                || ($gSettingsManager->getInt('forum_module_enabled') === 2 && $gValidLogin)) {
                    return true;
                }
                break;

            case 'LINKS':
                if ($gSettingsManager->getInt('weblinks_module_enabled') === 1
                || ($gSettingsManager->getInt('weblinks_module_enabled') === 2 && $gValidLogin)) {
                    return true;
                }
                break;

            case 'GROUPS-ROLES':
                if ($gSettingsManager->getBool('groups_roles_module_enabled') && $gValidLogin) {
                    return true;
                }
                break;

            case 'MESSAGES':
                if (($gSettingsManager->getInt('mail_module_enabled') === 1 || ($gSettingsManager->getInt('mail_module_enabled') === 2 && $gValidLogin))
                || ($gSettingsManager->getBool('pm_module_enabled') && $gValidLogin)) {
                    return true;
                }
                break;

            case 'PHOTOS':
                if ($gSettingsManager->getInt('photo_module_enabled') === 1
                || ($gSettingsManager->getInt('photo_module_enabled') === 2 && $gValidLogin)) {
                    return true;
                }
                break;

            case 'PROFILE':
                if ($gCurrentUser->hasRightViewProfile($gCurrentUser)) {
                    return true;
                }
                break;

            case 'REGISTRATION':
                if ($gSettingsManager->getBool('registration_module_enabled') && $gCurrentUser->isAdministratorRegistration()) {
                    return true;
                }
                break;

            case 'CATEGORIES': // fallthrough
            case 'MENU': // fallthrough
            case 'ORGANIZATIONS': // fallthrough
            case 'PREFERENCES': // fallthrough
            case 'PLUGINS': // fallthrough
            case 'ROOMS':
                if ($gCurrentUser->isAdministrator()) {
                    return true;
                }
                break;

            default:
                /*
                 * Everything that is not a component of Admidio itself is a plugin, whose
                 * com_name_intern is its ID. This answer is needed for every menu node of every
                 * request, so it reads the cached discovery of the registry and never loads or
                 * instantiates a plugin.
                 */
                $plugin = PluginRegistry::get($componentName);
                if ($plugin !== null && PluginRegistry::isEnabled($componentName)) {
                    /*
                     * A plugin that follows the Admidio convention expresses who may see it in an
                     * access preference of its own, and one that declares none is visible as soon
                     * as it is enabled. The preference is asked for by name rather than through the
                     * widget declaration of the plugin, because the answer must not depend on
                     * whether the plugin happens to be loaded in this request.
                     */
                    return PluginWidget::isVisible($plugin->getAccessSettingName());
                }
                break;
        }

        return false;
    }
}
