<?php
/**
 * Vercel build script for Ghana Council e.V.
 *
 * Reads database credentials from environment variables defined in vercel.json.
 * For the demo deployment all values are pre-filled.
 * For production, override them in Vercel → Project Settings → Environment Variables.
 */

$dbHost = getenv('DB_HOST') ?: '';
$dbPort = getenv('DB_PORT');
$dbName = getenv('DB_NAME') ?: 'gcm_demo';
$dbUser = getenv('DB_USER') ?: 'gcm_demo';
$dbPass = getenv('DB_PASS') ?: 'GcmDemo@2024';

$portValue = ($dbPort !== false && $dbPort !== '') ? (int)$dbPort : 'null';

$config = <<<PHP
<?php
/**
 * Admidio Configuration — Ghana Council e.V. (Demo)
 * Website: https://www.ghanacouncil-nrw.de
 *
 * Generated by Vercel build — do not edit manually.
 */

\$gDbType       = 'pgsql';
\$g_tbl_praefix = 'adm';

\$g_adm_srv  = '{$dbHost}';
\$g_adm_port = {$portValue};
\$g_adm_db   = '{$dbName}';
\$g_adm_usr  = '{$dbUser}';
\$g_adm_pw   = '{$dbPass}';

\$g_root_path = 'https://www.ghanacouncil-nrw.de';
\$gTimezone   = 'Europe/Berlin';
PHP;

$configDir  = __DIR__ . '/../../adm_my_files';
$configPath = $configDir . '/config.php';

if (!is_dir($configDir)) {
    mkdir($configDir, 0755, true);
}

if (file_put_contents($configPath, $config) === false) {
    echo "ERROR: Could not write to {$configPath}\n";
    exit(1);
}

echo "✓ Generated adm_my_files/config.php\n";
echo "  Organisation : Ghana Council e.V.\n";
echo "  Root path    : https://www.ghanacouncil-nrw.de\n";
echo "  DB host      : {$dbHost}\n";
echo "  DB name      : {$dbName}\n";
