<?php
/**
 * Vercel build script for Ghana Council e.V.
 *
 * Generates adm_my_files/config.php from Vercel environment variables.
 * Set the following secrets in your Vercel project:
 *   DB_HOST  - Database server hostname
 *   DB_PORT  - Database port (optional, leave blank for default)
 *   DB_NAME  - Database name
 *   DB_USER  - Database username
 *   DB_PASS  - Database password
 */

$dbHost = getenv('DB_HOST') ?: '';
$dbPort = getenv('DB_PORT');
$dbName = getenv('DB_NAME') ?: '';
$dbUser = getenv('DB_USER') ?: '';
$dbPass = getenv('DB_PASS') ?: '';

$portValue = ($dbPort !== false && $dbPort !== '') ? (int)$dbPort : 'null';

if (!$dbHost || !$dbName || !$dbUser) {
    echo "WARNING: One or more required database environment variables (DB_HOST, DB_NAME, DB_USER) are not set.\n";
    echo "         The application will not connect to the database without them.\n";
}

$config = <<<PHP
<?php
/**
 * Admidio Configuration for Ghana Council e.V.
 * Website: https://www.ghanacouncil-nrw.de
 *
 * Generated by Vercel build — do not edit manually.
 */

\$gDbType       = 'mysql';
\$g_tbl_praefix = 'adm';

\$g_adm_srv  = '{$dbHost}';
\$g_adm_port = {$portValue};
\$g_adm_db   = '{$dbName}';
\$g_adm_usr  = '{$dbUser}';
\$g_adm_pw   = '{$dbPass}';

\$g_root_path = 'https://www.ghanacouncil-nrw.de';
\$gTimezone   = 'Europe/Berlin';
PHP;

$configDir  = __DIR__ . '/../adm_my_files';
$configPath = $configDir . '/config.php';

if (!is_dir($configDir)) {
    mkdir($configDir, 0755, true);
}

if (file_put_contents($configPath, $config) === false) {
    echo "ERROR: Could not write to {$configPath}\n";
    exit(1);
}

echo "✓ Generated adm_my_files/config.php for Ghana Council e.V.\n";
echo "  Root path : https://www.ghanacouncil-nrw.de\n";
echo "  DB host   : {$dbHost}\n";
echo "  DB name   : {$dbName}\n";
