name: "Build branches"
on:
    push:
        # Sequence of patterns matched against refs/heads
        branches:
            - "master"
            - "v4.3"
            # - 'releases/**'
        # Sequence of patterns matched against refs/tags
        # tags:
        #     - "v*"
        # schedule:
        #     - cron: '00 5 * * 0'

permissions:
    contents: read

# env:
#     ADMIDIO_TRIVY_ENABLED: "true"

jobs:

    push_to_registry:
        if: github.repository == 'admidio/admidio'
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4
    
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: admidio/admidio
    
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
